before_script:
  - lsb_release -a
  - cmake --version

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

gcc 7:
  image: "registry.gitlab.com/katana-steel/lithtech/gcc"
  stage: test
  script:
    - g++ --version
    - mkdir build
    - cd build
    - cmake -G Ninja -DJSON_BuildTests=off ..
    - cmake --build .
clang 5:
  image: "registry.gitlab.com/katana-steel/lithtech/clang"
  stage: test
  script:
    - clang --version
    - mkdir build
    - cd build
    - cmake -G Ninja -DJSON_BuildTests=off ..
    - cmake --build .
