before_script:
  - apt-get -qq update && apt-get install -y -qq cmake make lsb-release libsdl2-dev
  - lsb_release -a
  - cmake --version

stages:
  - test

gcc 7:
  image: "gcc:7"
  stage: test
  script:
    - g++ --version
    - mkdir build
    - cd build
    - cmake ..
    - make
clang 5:
  image: "clang:5"
  stage: test
  script:
    - clang --version
    - mkdir build
    - cd build
    - cmake ..
    - make
