language: cpp
sudo: false
branch:
  only:
    - linux-x86_64

install: true

script:
  - cd Build
  - cmake -DJSON_BuildTests=off ../
  - make -j4 2>&1 | tee make.log
  - for part in $(grep 'Target rules' Makefile| awk '/_|Dir/ {print $NF}'); do make $part > /dev/null 2>&1 && echo Pass $part || echo Fail $part; done > build.log
  - cat build.log
  - "cat make.log build.log > make.build.log"
  - "python3 ../tests/validate.py make.build.log"
  - OUT/testRegMgr
  - "python3 -m json.tool LithTech.reg.json"
  - OUT/testDynRes tests/DynResDLL/libtestCRes.so
  - OUT/testDynRes NOLF2/ClientRes/TO2/libCRes.so
matrix:
  allow_failures:
    - clang: 4.0
    - clang: 7.0
    - gcc: "6 32bit"
    - gcc: 9
  include:
    - os: linux
      dist: bionic
      gcc: 8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - cmake-data
            - cmake
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
      env:
        - MATRIX_EVAL="CC=gcc-9; CXX=g++-9"
    - os: linux
      dist: trusty
      gcc: 6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake-data
            - cmake
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
      env:
        - MATRIX_EVAL="CC=gcc-6; CXX=g++-6"
    - os: linux
      dist: trusty
      gcc: 7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake-data
            - cmake
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
      env:
        - MATRIX_EVAL="CC=gcc-7; CXX=g++-7"
    - os: linux
      dist: trusty
      gcc: "6 32bit"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-multilib
            - libstdc++-6-dev:i386
            - cmake-data
            - cmake
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-image-dev:i386
            - libsdl2-mixer-dev
            - libsdl2-mixer-dev:i386
            - libsdl2-2.0-0
            - libsdl2-dev:i386
            - libsdl2-2.0-0:i386
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libwayland-egl1-mesa-lts-xenial
      env:
        - MATRIX_EVAL="CC=gcc-6; CXX=g++-6; CFLAGS=-m32; CXXFLAGS=-m32; LDFLAGS=-m32"
    - os: linux
      dist: trusty
      clang: 4.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cmake-data
            - cmake
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0; CXX=clang++-4.0"
    - os: linux
      clang: 7.0
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7.0
          packages:
            - clang-7.0
            - cmake-data
            - cmake
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
      env:
        - MATRIX_EVAL="CC=clang-7.0; CXX=clang++-7.0"


before_install:
    - eval "${MATRIX_EVAL}"
    - mkdir Build

