language: cpp
sudo: false
branch:
  only:
    - linux-x86_64
compiler:
  - gcc

install: true

script:
  - cd Build
  - cmake ../
  - for part in $(grep 'Target rules' Makefile| awk '{print $NF}'); do make $part >> make.log 2>&1 && echo Pass $part || echo Fail $part; done | tee -a build.log
  - "cat make.log build.log > make.build.log"
  - "python3 ../tests/validate.py make.build.log 13 10 110 95"
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake-data
            - cmake
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5""
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake-data
            - cmake
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"
    - mkdir Build

