language: cpp
sudo: true
branch:
  only:
    - linux-x86_64
compiler:
  - gcc

install: true

script:
  - cd Build
  - cmake ../
  - for part in $(grep 'Target rules' Makefile| awk '{print $NF}'); do make $part >/dev/null 2>&1 && echo Pass $part || echo Fail $part; done | tee build.log
  - echo Fail count: $(grep -c Fail build.log)
  - echo Pass count: $(grep -c Pass build.log)

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5""
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-6
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo add-apt-repository -y ppa:team-xbmc/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -y  libsdl2-dev
    - mkdir Build

