language: cpp
sudo: false
branch:
  only:
    - linux-x86_64
compiler:
  - gcc

install: true

script:
  - cd Build
  - cmake ../
  - for part in $(grep 'Target rules' Makefile| awk '{print $NF}'); do make -j4 $part >> make.build.log 2>&1 && echo Pass $part || echo Fail $part; done | tee make.build.build.log
  - "echo Fail  count: $(awk '{if ($1 == \"Fail\") total += 1 } END {print total}' make.build.log)"
  - "echo Pass  count: $(awk '{if ($1 == \"Pass\") total += 1 } END {print total}' make.build.log)"
  - "echo UnDef count: $(sort -u make.build.log | awk '{if ($0 ~ /undefined reference/) total += 1 } END {print total}')"
  # - "../test/check_build.py make.build.log 10 13 95"
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake-data
            - cmake
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5""
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake-data
            - cmake
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"
    - mkdir Build

