name: CMake

on:
  push:
    branches: [ linux-x86_64 ]
  pull_request:
    branches: [ linux-x86_64 ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    container:
      image: registry.gitlab.com/katana-steel/lithtech/gcc
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: build/
      run: | 
        OUT/testRegMgr
        OUT/testDynRes tests/DynResDLL/libtestCRes.so
        OUT/testDynRes NOLF2/ClientRes/TO2/libCRes.so
      
